---
name: automerge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  print-debug-info:
    name: Print debug info
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

  check-pr:
    name: CHeck
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          gh pr list --head ${{ github.event.workflow_run.head_branch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-mergeability:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: networkservicemesh/.github/.github/workflows/check-mergeability.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    needs: [check-mergeability]
    if: ${{ needs.check-mergeability.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Fetch main
        run: |
          git remote -v
          git fetch --depth=1 origin main
      - name: Check allowed files
        run: |
          find . -type f ! -name 'go.mod' ! -name 'go.sum' ! -name '*.yaml' ! -name '*.yml' ! -name '*.txt' ! -name '*.md' ! -name '*.conf' ! -name 'Dockerfile' -exec git diff --exit-code origin/main -- {} +
      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.workflow_run.head_branch }} --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  resolve_conflicts:
    needs: [check-mergeability]
    if: ${{ always() && needs.check-mergeability.result == 'failure' && needs.check-mergeability.outputs.pr_branch_ref != '' }}
    uses: networkservicemesh/.github/.github/workflows/resolve-conflicts.yaml@main
    with:
      pr_branch_ref: ${{ needs.check-mergeability.outputs.pr_branch_ref }}
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
