---
name: Release

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  create-release:
    uses: NikitaSkrynnik/.github/.github/workflows/release.yaml@cli-release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
