---
name: Release

on:
  push:
    branches:
      - 'release/**' 
jobs:
  create-release:
    uses: NikitaSkrynnik/.github/.github/workflows/release.yaml@cli-release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
